### ISSUE TITLE
crash windows

### ISSUE THREAD

**Issue by yoavst** [codeguru-il/corewars8086#12]
```
java.io.IOException: Cannot run program "ndisasm": CreateProcess error=2, The sy
stem cannot find the file specified
        at java.lang.ProcessBuilder.start(Unknown Source)
        at il.co.codeguru.corewars8086.utils.Disassembler.disassembler(Disassemb
ler.java:24)
        at il.co.codeguru.corewars8086.gui.CpuFrame.updateFileds(CpuFrame.java:1
92)
        at il.co.codeguru.corewars8086.gui.CpuFrame.onEndRound(CpuFrame.java:275
)
        at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at il.co.codeguru.corewars8086.utils.EventMulticaster$MulticasterInvocat
ionHandler.invoke(EventMulticaster.java:69)
        at com.sun.proxy.$Proxy1.onEndRound(Unknown Source)
        at il.co.codeguru.corewars8086.war.Competition.runWar(Competition.java:8
0)
        at il.co.codeguru.corewars8086.war.Competition.runCompetition(Competitio
n.java:55)
        at il.co.codeguru.corewars8086.gui.CompetitionWindow$3.run(CompetitionWi
ndow.java:137)
Caused by: java.io.IOException: CreateProcess error=2, The system cannot find th
e file specified
        at java.lang.ProcessImpl.create(Native Method)
        at java.lang.ProcessImpl.<init>(Unknown Source)
        at java.lang.ProcessImpl.start(Unknown Source)
        ... 12 more
java.io.IOException: Cannot run program "ndisasm": CreateProcess error=2, The sy
stem cannot find the file specified
        at java.lang.ProcessBuilder.start(Unknown Source)
        at il.co.codeguru.corewars8086.utils.Disassembler.disassembler(Disassemb
ler.java:24)
        at il.co.codeguru.corewars8086.gui.CpuFrame.updateFileds(CpuFrame.java:1
92)
        at il.co.codeguru.corewars8086.gui.CpuFrame.onEndRound(CpuFrame.java:275
)
        at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at il.co.codeguru.corewars8086.utils.EventMulticaster$MulticasterInvocat
ionHandler.invoke(EventMulticaster.java:69)
        at com.sun.proxy.$Proxy1.onEndRound(Unknown Source)
        at il.co.codeguru.corewars8086.war.Competition.runWar(Competition.java:8
0)
        at il.co.codeguru.corewars8086.war.Competition.runCompetition(Competitio
n.java:55)
        at il.co.codeguru.corewars8086.gui.CompetitionWindow$3.run(CompetitionWi
ndow.java:137)
Caused by: java.io.IOException: CreateProcess error=2, The system cannot find th
e file specified
        at java.lang.ProcessImpl.create(Native Method)
        at java.lang.ProcessImpl.<init>(Unknown Source)
        at java.lang.ProcessImpl.start(Unknown Source)
        ... 12 more
java.io.IOException: Cannot run program "ndisasm": CreateProcess error=2, The sy
stem cannot find the file specified
        at java.lang.ProcessBuilder.start(Unknown Source)
        at il.co.codeguru.corewars8086.utils.Disassembler.disassembler(Disassemb
ler.java:24)
        at il.co.codeguru.corewars8086.gui.CpuFrame.updateFileds(CpuFrame.java:1
92)
        at il.co.codeguru.corewars8086.gui.CpuFrame.onEndRound(CpuFrame.java:275
)
        at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at il.co.codeguru.corewars8086.utils.EventMulticaster$MulticasterInvocat
ionHandler.invoke(EventMulticaster.java:69)
        at com.sun.proxy.$Proxy1.onEndRound(Unknown Source)
        at il.co.codeguru.corewars8086.war.Competition.runWar(Competition.java:8
0)
        at il.co.codeguru.corewars8086.war.Competition.runCompetition(Competitio
n.java:55)
        at il.co.codeguru.corewars8086.gui.CompetitionWindow$3.run(CompetitionWi
ndow.java:137)
Caused by: java.io.IOException: CreateProcess error=2, The system cannot find th
e file specified
        at java.lang.ProcessImpl.create(Native Method)
        at java.lang.ProcessImpl.<init>(Unknown Source)
        at java.lang.ProcessImpl.start(Unknown Source)
        ... 12 more
java.io.IOException: Cannot run program "ndisasm": CreateProcess error=2, The sy
stem cannot find the file specified
        at java.lang.ProcessBuilder.start(Unknown Source)
        at il.co.codeguru.corewars8086.utils.Disassembler.disassembler(Disassemb
ler.java:24)
        at il.co.codeguru.corewars8086.gui.CpuFrame.updateFileds(CpuFrame.java:1
92)
        at il.co.codeguru.corewars8086.gui.CpuFrame.onEndRound(CpuFrame.java:275
)
        at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at il.co.codeguru.corewars8086.utils.EventMulticaster$MulticasterInvocat
ionHandler.invoke(EventMulticaster.java:69)
        at com.sun.proxy.$Proxy1.onEndRound(Unknown Source)
        at il.co.codeguru.corewars8086.war.Competition.runWar(Competition.java:8
0)
        at il.co.codeguru.corewars8086.war.Competition.runCompetition(Competitio
n.java:55)
        at il.co.codeguru.corewars8086.gui.CompetitionWindow$3.run(CompetitionWi
ndow.java:137)
Caused by: java.io.IOException: CreateProcess error=2, The system cannot find th
e file specified
        at java.lang.ProcessImpl.create(Native Method)
        at java.lang.ProcessImpl.<init>(Unknown Source)
        at java.lang.ProcessImpl.start(Unknown Source)
        ... 12 more
java.io.IOException: Cannot run program "ndisasm": CreateProcess error=2, The sy
stem cannot find the file specified
        at java.lang.ProcessBuilder.start(Unknown Source)
        at il.co.codeguru.corewars8086.utils.Disassembler.disassembler(Disassemb
ler.java:24)
        at il.co.codeguru.corewars8086.gui.CpuFrame.updateFileds(CpuFrame.java:1
92)
        at il.co.codeguru.corewars8086.gui.CpuFrame.onEndRound(CpuFrame.java:275
)
        at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at il.co.codeguru.corewars8086.utils.EventMulticaster$MulticasterInvocat
ionHandler.invoke(EventMulticaster.java:69)
        at com.sun.proxy.$Proxy1.onEndRound(Unknown Source)
        at il.co.codeguru.corewars8086.war.Competition.runWar(Competition.java:8
0)
        at il.co.codeguru.corewars8086.war.Competition.runCompetition(Competitio
n.java:55)
        at il.co.codeguru.corewars8086.gui.CompetitionWindow$3.run(CompetitionWi
ndow.java:137)
Caused by: java.io.IOException: CreateProcess error=2, The system cannot find th
e file specified
        at java.lang.ProcessImpl.create(Native Method)
        at java.lang.ProcessImpl.<init>(Unknown Source)
        at java.lang.ProcessImpl.start(Unknown Source)
        ... 12 more
```

**Comment by yoavst** [comment]
I think it is better to include nasm in path.

**Comment by rmkn85** [comment]
ndisasm should be in your path if you want to use disassembler window
you can't include it with the project since it can be in windows or linux which have different executables

in the next version that i'm working on, the disassembler will be integrated into the engine, so no external executable will be required
